name:                HypixelAuctionTracker
version:             0.1.0.0
github:              "XanderDJ/HypixelAuctionTracker"
license:             BSD3
author:              "Xander De Jaegere"
maintainer:          "x.de.j@hotmail.com"
copyright:           "2019 Xander De Jaegere"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/XanderDJ/HypixelAuctionTracker#readme>

dependencies:
- base >= 4.7 && < 5
- mongoDB
- http-client
- http-client-tls
- http-types
- aeson
- bytestring
- text
- mtl
- hledger-lib 
- nbt
- cereal
- zlib
- base64-bytestring
- array

library:
  source-dirs: src

executables:
  HypixelAuctionTracker-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HypixelAuctionTracker

tests:
  HypixelAuctionTracker-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HypixelAuctionTracker
